export const code = [
    {
        "image":"/Feed/code/fotis-fotopoulos-LJ9KY8pIH3E-unsplash.jpg",
        "name":"two-monitors",
        "category":"code",
        "time":"30"
    },
    {
        "image":"/Feed/code/kevin-horvat-Pyjp2zmxuLk-unsplash.jpg",
        "name":"hacker",
        "category":"code",
        "time":"29"
    },
    {
        "image":"/Feed/code/nubelson-fernandes-gTs2w7bu3Qo-unsplash.jpg",
        "name":"programming",
        "category":"code",
        "time":"28"
    },
    {
        "image":"/Feed/code/michael-marais-y9emxVhxeTM-unsplash.jpg",
        "name":"code",
        "category":"code",
        "time":"22"
    },
    {
        "image":"/Feed/code/kevin-ku-w7ZyuGYNpRQ-unsplash.jpg",
        "name":"glasses with monitors",
        "category":"code",
        "time":"10"
    },
]