export const mobile = [
    {
        "image":"/Feed/mobile/ben-kolde-cpLsWmMEa1Q-unsplash.jpg",
        "name":"ben-kolde",
        "category":"mobile",
        "time":"25"
    },
    {
        "image":"/Feed/mobile/daniel-romero-4P3jflrqJhA-unsplash.jpg",
        "name":"xiaomi",
        "category":"mobile",
        "time":"25"
    },
    {
        "image":"/Feed/mobile/mailchimp-KR0WW6bjtt0-unsplash.jpg",
        "name":"mailchimp",
        "category":"mobile",
        "time":"27"
    },
    {
        "image":"/Feed/mobile/d-c-tr-nh-NEv65ZXjuLg-unsplash.jpg",
        "name":"iphones",
        "category":"mobile",
        "time":"24"
    },
    {
        "image":"/Feed/mobile/sun-lingyan-k7lb5oYYYAw-unsplash.jpg",
        "name":"xiaomi",
        "category":"mobile",
        "time":"14"
    },
]